/**
 * Schema migrations, with EXPLICIT recorded state.
 *
 * What this replaces: until order L-3.4g the schema was a pile of
 * `CREATE TABLE IF NOT EXISTS` plus hand-rolled `addColumnIfMissing` /
 * `PRAGMA table_info` guards, and storeDiscoveryDb.ts said so out loud —
 * "There is no migration framework here". That worked because SQLite was
 * forgiving and because the file was recreated from scratch on every publish
 * anyway. Against a database that actually persists, "the schema is whatever
 * the last boot happened to add" is not a state anybody can reason about.
 *
 * So: an ordered list, each entry applied exactly once, inside a transaction,
 * with its id and name written to `schema_migrations` in the SAME transaction.
 * Either a migration and its record both land or neither does.
 *
 * TYPE MAPPING, applied uniformly (see the ledger for the table-by-table map):
 *   TEXT                            → text
 *   INTEGER                         → bigint
 *   REAL                            → double precision
 *   INTEGER PRIMARY KEY AUTOINCREMENT → bigint GENERATED BY DEFAULT AS IDENTITY
 *
 * `INTEGER → bigint` is not caution for its own sake. SQLite's INTEGER is
 * 64-bit and this schema stores epoch MILLISECONDS in it; `int4` tops out at
 * 2147483647, which epoch-ms passed in 1970. A column of `integer` here would
 * take every timestamp write in the app and turn it into an out-of-range error.
 *
 * `GENERATED BY DEFAULT AS IDENTITY` rather than `ALWAYS`: the rescue seed
 * (rescueSeed.ts) inserts `job_results` rows under their ORIGINAL ids so that
 * `lf_lead_id` keeps pointing at the same lead the Chief already recorded, and
 * `ALWAYS` would refuse those inserts.
 *
 * COLUMN ORDER IS LOAD-BEARING. `getJob` and friends `SELECT *`, and those rows
 * are serialised straight into API responses, so column order is JSON key order
 * and the DARK smoke baseline pins it. Every table below lists its columns in
 * the order the SQLite database had them — base CREATE first, then the columns
 * that arrived later by ALTER, in the order they arrived.
 *
 * THE STANDING RULE: a migration containing DROP or TRUNCATE is never approved.
 * That is not a convention here — assertNoDestructiveMigrations() below is run
 * by the test gate, so a destructive migration cannot reach a database at all.
 */

import type { Db, SqlHandle } from './sql.js';
import { log } from './logger.js';

export interface Migration {
  id: number;
  name: string;
  sql: string;
}

/**
 * 001 — the baseline.
 *
 * This is the SQLite schema as it stood at the moment of the port, with every
 * additive ALTER already folded into the table it belonged to. There is no
 * "upgrade an old database" path in it because there is no old PostgreSQL
 * database: this app's history lived on a deployment disk that did not survive.
 */
const BASELINE = `
  ---------------------------------------------------------------- jobs
  CREATE TABLE jobs (
    id                text PRIMARY KEY,
    product_type      text NOT NULL,
    countries         text NOT NULL,
    status            text NOT NULL,
    csv_path          text,
    error             text,
    created_at        bigint NOT NULL,
    started_at        bigint,
    completed_at      bigint,
    total_ads_scraped bigint NOT NULL DEFAULT 0,
    total_advertisers bigint NOT NULL DEFAULT 0,
    -- columns that arrived by ALTER, in the order they arrived
    recipient_email     text,
    notification_status text,
    created_by_user_id  text,
    source              text NOT NULL DEFAULT 'meta',
    source_params       text,
    phase               text,
    phase_detail        text,
    phase_updated_at    bigint,
    hq_zip_path         text,
    run_after           bigint,
    cancel_requested    bigint NOT NULL DEFAULT 0,
    leads_found         bigint NOT NULL DEFAULT 0,
    progress_pct        double precision NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_jobs_status ON jobs(status);
  CREATE INDEX idx_jobs_user ON jobs(created_by_user_id);

  ---------------------------------------------------------------- job_logs
  CREATE TABLE job_logs (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id  text NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    level   text NOT NULL,
    message text NOT NULL,
    ts      bigint NOT NULL
  );
  CREATE INDEX idx_job_logs_job ON job_logs(job_id, ts);

  ---------------------------------------------------------------- job_results
  CREATE TABLE job_results (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          text NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    advertiser_name text NOT NULL,
    page_url        text,
    landing_url     text,
    classification  text,
    store_url       text,
    ad_text         text,
    country         text NOT NULL,
    created_at      bigint NOT NULL,
    -- app-category enrichment, added by ALTER after the fact
    app_category    text,
    is_game         bigint
  );
  CREATE INDEX idx_job_results_job ON job_results(job_id);

  ---------------------------------------------------------------- settings
  CREATE TABLE settings (
    key        text PRIMARY KEY,
    value      text NOT NULL,
    updated_at bigint NOT NULL
  );

  ---------------------------------------------------------------- users
  CREATE TABLE users (
    id                text PRIMARY KEY,
    email             text NOT NULL UNIQUE,
    name              text,
    default_recipient text,
    created_at        bigint NOT NULL
  );

  ---------------------------------------------------------------- sessions
  CREATE TABLE sessions (
    token      text PRIMARY KEY,
    user_id    text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL
  );

  ---------------------------------------------------------------- gmail_tokens
  CREATE TABLE gmail_tokens (
    user_id       text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    access_token  text,
    refresh_token text,
    expires_at    bigint,
    gmail_email   text,
    updated_at    bigint NOT NULL
  );

  ---------------------------------------------------------------- llm_spend
  CREATE TABLE llm_spend (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts                 bigint NOT NULL,
    spend_day          text NOT NULL,
    source             text NOT NULL,
    model              text NOT NULL,
    input_tokens       bigint NOT NULL DEFAULT 0,
    output_tokens      bigint NOT NULL DEFAULT 0,
    cache_write_tokens bigint NOT NULL DEFAULT 0,
    cache_read_tokens  bigint NOT NULL DEFAULT 0,
    web_searches       bigint NOT NULL DEFAULT 0,
    usd                double precision NOT NULL
  );
  CREATE INDEX idx_llm_spend_day ON llm_spend(spend_day);

  ---------------------------------------------------------------- chief_jobs
  -- The Chief's idempotency ledger. external_id is the PRIMARY KEY and
  -- PostgreSQL's default collations are DETERMINISTIC, so '=' is byte equality
  -- exactly as SQLite's BINARY collation was: ' x', 'x' and 'X' remain three
  -- different keys. chief.ts's suite proves it against the live engine.
  CREATE TABLE chief_jobs (
    external_id text PRIMARY KEY,
    job_id      text NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE CASCADE,
    created_at  bigint NOT NULL
  );

  ---------------------------------------------------------------- hq_cache
  CREATE TABLE hq_cache (
    store_url     text PRIMARY KEY,
    resolved_json text NOT NULL,
    created_at    bigint NOT NULL
  );

  ------------------------------------------------------- app_category_cache
  CREATE TABLE app_category_cache (
    app_id            text PRIMARY KEY,
    store             text NOT NULL,
    category_raw      text,
    is_game           bigint,
    enrichment_source text,
    failed            bigint NOT NULL DEFAULT 0,
    attempts          bigint NOT NULL DEFAULT 0,
    created_at        bigint NOT NULL
  );

  ---------------------------------------------------------- discovered_apps
  CREATE TABLE discovered_apps (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store             text NOT NULL,
    app_id            text NOT NULL,
    title             text,
    vertical          text,
    country           text NOT NULL,
    source            text NOT NULL,
    discovery_depth   bigint NOT NULL DEFAULT 0,
    chart             text,
    rank              bigint,
    first_seen_at     bigint NOT NULL,
    last_seen_at      bigint NOT NULL,
    last_rank         bigint,
    list_developer    text,
    list_developer_id text,
    UNIQUE (store, app_id, country)
  );
  CREATE INDEX idx_discovered_apps_appid ON discovered_apps(store, app_id);
  CREATE INDEX idx_discovered_apps_vertical ON discovered_apps(vertical, source);
  CREATE INDEX idx_discovered_apps_listdev ON discovered_apps(store, list_developer);
  CREATE INDEX idx_discovered_depth ON discovered_apps(store, source, discovery_depth);

  --------------------------------------------------------- store_app_detail
  CREATE TABLE store_app_detail (
    store              text NOT NULL,
    app_id             text NOT NULL,
    title              text,
    developer          text,
    developer_id       text,
    developer_email    text,
    developer_website  text,
    min_installs       bigint,
    genre_id           text,
    category_raw       text,
    is_game            bigint,
    store_updated_at   bigint,
    artist_id          text,
    seller_name        text,
    bundle_id          text,
    enrich_status      text NOT NULL DEFAULT 'failed',
    attempts           bigint NOT NULL DEFAULT 0,
    last_live_check_at bigint,
    delisted_at        bigint,
    created_at         bigint NOT NULL,
    updated_at         bigint NOT NULL,
    PRIMARY KEY (store, app_id)
  );
  CREATE INDEX idx_store_app_detail_dev ON store_app_detail(developer_id);

  ---------------------------------------------------------------- publishers
  CREATE TABLE publishers (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merge_key            text NOT NULL UNIQUE,
    name                 text NOT NULL,
    play_developer_id    text,
    apple_seller_name    text,
    website              text,
    email                text,
    countries_charted    text NOT NULL DEFAULT '[]',
    countries_seen       text NOT NULL DEFAULT '[]',
    verticals            text NOT NULL DEFAULT '[]',
    charted_app_count    bigint NOT NULL DEFAULT 0,
    app_count            bigint NOT NULL DEFAULT 0,
    best_rank            bigint,
    both_stores          bigint NOT NULL DEFAULT 0,
    in_band              bigint NOT NULL DEFAULT 0,
    source_mix           text NOT NULL DEFAULT '{}',
    gatc_advertiser_id   text,
    gatc_ads_count       bigint,
    meta_active_ads      bigint,
    confirmed_advertiser bigint NOT NULL DEFAULT 0,
    is_game_publisher    bigint NOT NULL DEFAULT 0,
    is_charted           bigint NOT NULL DEFAULT 0,
    preview_url          text,
    preview_title        text,
    score                double precision NOT NULL DEFAULT 0,
    last_confirm_at      bigint,
    created_at           bigint NOT NULL,
    updated_at           bigint NOT NULL
  );
  CREATE INDEX idx_publishers_score ON publishers(score DESC);
  CREATE INDEX idx_publishers_playdev ON publishers(play_developer_id);
  CREATE INDEX idx_publishers_seller ON publishers(apple_seller_name);

  ------------------------------------------------------- publisher_identity
  CREATE TABLE publisher_identity (
    identity_key text PRIMARY KEY,
    publisher_id bigint NOT NULL
  );
  CREATE INDEX idx_publisher_identity_pub ON publisher_identity(publisher_id);

  ----------------------------------------------- developer_catalog_expansion
  CREATE TABLE developer_catalog_expansion (
    store            text NOT NULL,
    developer_id     text NOT NULL,
    last_expanded_at bigint NOT NULL,
    PRIMARY KEY (store, developer_id)
  );

  ------------------------------------------------------- search_battery_cell
  CREATE TABLE search_battery_cell (
    vertical         text NOT NULL,
    market           text NOT NULL,
    term             text NOT NULL,
    last_searched_at bigint NOT NULL,
    PRIMARY KEY (vertical, market, term)
  );

  ------------------------------------------------- search_battery_cell_store
  CREATE TABLE search_battery_cell_store (
    store            text NOT NULL,
    vertical         text NOT NULL,
    market           text NOT NULL,
    term             text NOT NULL,
    last_searched_at bigint NOT NULL,
    PRIMARY KEY (store, vertical, market, term)
  );

  ------------------------------------------------------- similar_crawl_seed
  CREATE TABLE similar_crawl_seed (
    store           text NOT NULL,
    app_id          text NOT NULL,
    last_crawled_at bigint NOT NULL,
    PRIMARY KEY (store, app_id)
  );
`;

/**
 * 002 — the Chief spend-reporting cursor (order L-3.5a).
 *
 * What has been reported to the Chief, per UTC day per vendor, counted in
 * whole $0.50 quanta. The reporter emits one request per quantum and advances
 * this row in the SAME transaction as the request it just got a 2xx for, so a
 * restart at any instant never double-reports and never loses a quantum.
 *
 * The day here is UTC, unlike `llm_spend.spend_day`, which is Asia/Jerusalem.
 * That is deliberate and decided: the Chief's fleet contract counts UTC days,
 * while this app's own $100 cap resets at Jerusalem midnight. Both windows are
 * real, they differ by three hours, and each is named wherever it is served.
 * The UTC day is derived from `llm_spend.ts` — an absolute epoch-ms stamp — so
 * this is the same ledger read on a different boundary, never a second source
 * of spend truth.
 *
 * `reported_quanta` is a count, not an amount: it is exact in integers, where
 * a running USD total accumulated in binary floating point would not be.
 */
const CHIEF_SPEND_CURSOR = `
  -------------------------------------------------------- chief_spend_cursor
  CREATE TABLE chief_spend_cursor (
    utc_day         text NOT NULL,
    vendor          text NOT NULL,
    reported_quanta bigint NOT NULL DEFAULT 0,
    updated_at      bigint NOT NULL,
    PRIMARY KEY (utc_day, vendor)
  );

  -- The reporter sums a UTC day as a RANGE over llm_spend.ts, because the only
  -- indexed column, spend_day, carries the Jerusalem day. Without this index
  -- every sweep is a sequential scan that grows with the ledger forever.
  CREATE INDEX idx_llm_spend_ts ON llm_spend(ts);
`;

export const MIGRATIONS: readonly Migration[] = [
  { id: 1, name: 'baseline schema ported from sqlite', sql: BASELINE },
  { id: 2, name: 'chief spend reporting cursor', sql: CHIEF_SPEND_CURSOR },
];

/** Every table the baseline owns — the set the adopt check looks for. */
export const BASELINE_TABLES: readonly string[] = [
  'jobs',
  'job_logs',
  'job_results',
  'settings',
  'users',
  'sessions',
  'gmail_tokens',
  'llm_spend',
  'chief_jobs',
  'hq_cache',
  'app_category_cache',
  'discovered_apps',
  'store_app_detail',
  'publishers',
  'publisher_identity',
  'developer_catalog_expansion',
  'search_battery_cell',
  'search_battery_cell_store',
  'similar_crawl_seed',
];

// ── The destructive-migration ban ────────────────────────────────────────────

/**
 * DROP and TRUNCATE are refused, statically, before anything runs.
 *
 * The fleet rule this encodes: a GENERATED migration containing DROP is never
 * approved. Tools that diff a model against a live schema emit
 * `DROP TABLE`/`DROP COLUMN` for anything they cannot see a reason for, and
 * approving one of those against a database that now holds the only copy of the
 * data is unrecoverable. Rather than trusting review to catch it, the test gate
 * calls this and fails.
 *
 * Comments are stripped first so the words can still be DISCUSSED in a comment
 * (this file does exactly that, several times).
 */
export function assertNoDestructiveMigrations(migrations: readonly Migration[] = MIGRATIONS): void {
  for (const m of migrations) {
    const bare = m.sql
      .replace(/--[^\n]*/g, ' ')
      .replace(/\/\*[\s\S]*?\*\//g, ' ');
    const hit = /\b(DROP|TRUNCATE)\b/i.exec(bare);
    if (hit) {
      throw new Error(
        `Migration ${m.id} (${m.name}) contains ${hit[1].toUpperCase()}. ` +
          'Destructive migrations are never approved in this repo — the database now ' +
          'holds the only copy of this app\'s state.',
      );
    }
  }
}

// ── Applying them ────────────────────────────────────────────────────────────

/**
 * Advisory-lock key for the migration step. An arbitrary constant — it only has
 * to be the same in every process that migrates THIS schema, and different from
 * any other advisory lock this app might take later (it takes none today).
 */
const MIGRATION_LOCK_KEY = 3420250807;

const STATE_TABLE = `
  CREATE TABLE IF NOT EXISTS schema_migrations (
    id         integer PRIMARY KEY,
    name       text NOT NULL,
    applied_at bigint NOT NULL
  );
`;

export interface MigrationOutcome {
  /** Ids applied by THIS boot, in order. Empty when the schema was current. */
  applied: number[];
  /** Ids recorded without running, because this boot adopted an existing schema. */
  adopted: number[];
  /** Every id the database now considers applied. */
  current: number[];
}

/** Which of our tables already exist, whatever the migration state says. */
async function existingBaselineTables(h: SqlHandle): Promise<string[]> {
  const rows = await h
    .prepare(
      `SELECT table_name FROM information_schema.tables
        WHERE table_schema = current_schema() AND table_name = ANY(?)
        ORDER BY table_name`,
    )
    .all<{ table_name: string }>(BASELINE_TABLES as string[]);
  return rows.map((r) => r.table_name);
}

/**
 * Bring the database up to date, or refuse.
 *
 * THE ADOPT PATH. A production database paired with this app at publish time
 * can already hold the baseline tables while `schema_migrations` is empty —
 * that is what happens when a schema was created by something other than this
 * migrator. Guessing is not an option: applying the baseline would fail
 * halfway through on the first table that already exists, and skipping it would
 * leave the app running against a schema nobody has checked.
 *
 * So that state is an explicit refusal, and the operator opts in for exactly
 * one boot with `LEADFINDER_DB_ADOPT=1`, which records the baseline as applied
 * WITHOUT running it. Nothing is created, altered or dropped by adopting.
 */
export async function applyMigrations(
  db: Db,
  opts: { adopt?: boolean; migrations?: readonly Migration[] } = {},
): Promise<MigrationOutcome> {
  const migrations = opts.migrations ?? MIGRATIONS;
  assertNoDestructiveMigrations(migrations);

  await db.exec(STATE_TABLE);

  const outcome: MigrationOutcome = { applied: [], adopted: [], current: [] };

  // ONE transaction for the whole set, opened with an advisory lock.
  //
  // The lock is what makes two processes racing to migrate the same database
  // safe — the loser waits, then re-reads the state inside the lock and finds
  // nothing pending. Without it the loser's CREATE TABLE fails with "relation
  // already exists" and the boot dies. This is not hypothetical here: the test
  // gate boots the assembly several times against one cluster, and the
  // persistence proof restarts the server on purpose.
  //
  // PostgreSQL DDL is transactional, so the whole baseline plus its record is
  // atomic: a migration that fails halfway leaves NO tables and NO state,
  // rather than a half-schema the next boot would try to adopt.
  await db.transaction(async (t) => {
    await t.prepare(`SELECT pg_advisory_xact_lock(?)`).run(MIGRATION_LOCK_KEY);

    const appliedRows = await t.prepare(`SELECT id FROM schema_migrations ORDER BY id`).all<{ id: number }>();
    const applied = new Set(appliedRows.map((r) => r.id));
    outcome.current = [...applied];

    const pending = migrations.filter((m) => !applied.has(m.id));
    if (pending.length === 0) return;

    // Is there already a schema here that this migrator did not record?
    //
    // ONLY when it has recorded NOTHING. The adopt path exists for one state: a
    // database whose schema was created by something other than this migrator,
    // so `schema_migrations` is empty while the tables are there. Once even one
    // migration is recorded, this migrator owns the schema and every later
    // migration simply runs.
    //
    // Gating on `pending.length > 0` instead — which is what this did until
    // order L-3.5a — breaks the moment a SECOND migration is ever added: the
    // production database has 001 recorded and all nineteen baseline tables, so
    // the pending 002 would trip the refusal and the app would not boot. Worse,
    // an operator following the error's own instruction would set
    // LEADFINDER_DB_ADOPT=1 and record 002 as applied WITHOUT running it,
    // leaving a table that no later boot would ever create. L-3.5a ships the
    // first post-baseline migration and is therefore the first order to trip it.
    const present = applied.size === 0 ? await existingBaselineTables(t) : [];
    if (present.length > 0) {
      if (!opts.adopt) {
        throw new Error(
          `This database already holds ${present.length} of this app's tables (${present.slice(0, 5).join(', ')}` +
            `${present.length > 5 ? ', …' : ''}) but has no migration state for them. ` +
            'Refusing to guess. If this schema was created by this app and is correct, restart ONCE with ' +
            'LEADFINDER_DB_ADOPT=1 to record migrations ' +
            `${pending.map((m) => m.id).join(', ')} as applied without running them. ` +
            'Nothing is created, altered or dropped by adopting.',
        );
      }
      for (const m of pending) {
        await t
          .prepare(`INSERT INTO schema_migrations (id, name, applied_at) VALUES (?, ?, ?)`)
          .run(m.id, m.name, Date.now());
        outcome.adopted.push(m.id);
        outcome.current.push(m.id);
      }
      return;
    }

    for (const m of pending) {
      await t.exec(m.sql);
      await t
        .prepare(`INSERT INTO schema_migrations (id, name, applied_at) VALUES (?, ?, ?)`)
        .run(m.id, m.name, Date.now());
      outcome.applied.push(m.id);
      outcome.current.push(m.id);
    }
  });

  for (const id of outcome.applied) {
    const m = migrations.find((x) => x.id === id)!;
    log.info(`db: applied migration ${m.id} — ${m.name}`);
  }
  if (outcome.adopted.length > 0) {
    log.warn(
      `db: ADOPTED an existing schema — migrations ${outcome.adopted.join(', ')} recorded as applied ` +
        'without running. Remove LEADFINDER_DB_ADOPT before the next boot.',
    );
  }

  return outcome;
}

// ── offline tests (pure — no database) ───────────────────────────────────────

export function runMigrationsTests(): { passed: number; failed: number; failures: string[] } {
  let passed = 0;
  const failures: string[] = [];
  const check = (cond: boolean, desc: string) => {
    if (cond) passed++;
    else failures.push(`FAIL: ${desc}`);
  };

  check(MIGRATIONS.length > 0, 'migrations: there is at least one');
  check(
    MIGRATIONS.every((m, i) => (i === 0 ? true : m.id > MIGRATIONS[i - 1].id)),
    'migrations: ids are strictly ascending',
  );
  check(new Set(MIGRATIONS.map((m) => m.id)).size === MIGRATIONS.length, 'migrations: ids are unique');
  check(
    MIGRATIONS.every((m) => m.name.trim().length > 0),
    'migrations: every migration is named',
  );

  // The ban, in both directions.
  let banned = false;
  try {
    assertNoDestructiveMigrations([{ id: 99, name: 'generated diff', sql: 'DROP TABLE publishers;' }]);
  } catch {
    banned = true;
  }
  check(banned, 'migrations: a DROP is refused');
  let truncBanned = false;
  try {
    assertNoDestructiveMigrations([{ id: 99, name: 'generated diff', sql: 'truncate table jobs;' }]);
  } catch {
    truncBanned = true;
  }
  check(truncBanned, 'migrations: a lower-case TRUNCATE is refused too');
  let dropColumn = false;
  try {
    assertNoDestructiveMigrations([
      { id: 99, name: 'generated diff', sql: 'ALTER TABLE jobs DROP COLUMN leads_found;' },
    ]);
  } catch {
    dropColumn = true;
  }
  check(dropColumn, 'migrations: DROP COLUMN is refused, not only DROP TABLE');

  let shipped = true;
  try {
    assertNoDestructiveMigrations();
  } catch {
    shipped = false;
  }
  check(shipped, 'migrations: the migrations this app actually ships are non-destructive');

  check(
    /-- .*DROP/i.test('-- a comment mentioning DROP') &&
      (() => {
        try {
          assertNoDestructiveMigrations([{ id: 99, name: 'commented', sql: '-- DROP is never approved\nSELECT 1;' }]);
          return true;
        } catch {
          return false;
        }
      })(),
    'migrations: the words may still be discussed in a comment',
  );

  // Every baseline table must actually appear in the baseline SQL, or the adopt
  // check would look for a table this migration never creates.
  const baselineSql = MIGRATIONS[0].sql;
  const missing = BASELINE_TABLES.filter((t) => !new RegExp(`CREATE TABLE ${t}\\b`).test(baselineSql));
  check(missing.length === 0, `migrations: every listed baseline table is created (missing: ${missing.join(', ')})`);

  // int4 would overflow on epoch-ms. Nothing in the baseline may be `integer`
  // except schema_migrations.id, which is not in this string at all.
  check(!/\binteger\b/i.test(baselineSql), 'migrations: no baseline column is int4 — epoch-ms needs bigint');

  // Identity columns must be BY DEFAULT, or the rescue seed cannot restore a
  // lead under the id the Chief already recorded.
  const identityCount = (baselineSql.match(/GENERATED BY DEFAULT AS IDENTITY/g) ?? []).length;
  check(identityCount === 5, `migrations: all five AUTOINCREMENT keys are BY DEFAULT identities (found ${identityCount})`);
  check(
    !/GENERATED ALWAYS AS IDENTITY/.test(baselineSql),
    'migrations: no identity is ALWAYS — the rescue seed inserts explicit ids',
  );

  // ── 002, the spend cursor (L-3.5a) ──
  const m2 = MIGRATIONS.find((m) => m.id === 2);
  check(!!m2, 'migrations: 002 is shipped');
  check(
    !!m2 && /CREATE TABLE chief_spend_cursor\b/.test(m2.sql),
    'migrations: 002 creates chief_spend_cursor',
  );
  check(
    !!m2 && /PRIMARY KEY \(utc_day, vendor\)/.test(m2.sql),
    'migrations: the cursor is keyed per UTC day per vendor',
  );
  check(
    !!m2 && !/\binteger\b/i.test(m2.sql),
    'migrations: 002 uses bigint, not int4 — updated_at is epoch-ms',
  );
  // The cursor is NOT a baseline table. Listing it would make the adopt check
  // look for a table migration 001 never creates.
  check(
    !BASELINE_TABLES.includes('chief_spend_cursor'),
    'migrations: the cursor is not claimed by the baseline',
  );

  return { passed, failed: failures.length, failures };
}

const isMain =
  typeof process !== 'undefined' &&
  process.argv[1] &&
  (process.argv[1].endsWith('migrations.js') || process.argv[1].endsWith('migrations.ts'));
if (isMain) {
  const { passed, failed, failures } = runMigrationsTests();
  console.log(`migrations tests: ${passed} passed, ${failed} failed`);
  for (const f of failures) console.log('  ' + f);
  process.exit(failed === 0 ? 0 : 1);
}
