/**
 * Seed the chief jobs rescued from the live deployment before the storage move.
 *
 * WHY THIS EXISTS
 * Two of the Chief's written promises hang on this app remembering jobs it has
 * already completed: same-key adoption (a repeated `external_id` must return
 * the job it already names, not start a second run) and the ICP backfill, which
 * reads `page_url`, `is_game` and `found_at` back out of this app through the
 * `lf_job_id` / `lf_lead_id` recorded on every Chief prospect.
 *
 * Both of those broke the moment the deployment's disk was replaced. Order
 * L-3.4g's first act was therefore to page the two named jobs off the LIVE seam
 * — read-only, `GET /api/chief/jobs/:id` and `/leads` — and commit what came
 * back as fixtures. This module puts them back into the database that survives.
 *
 * WHAT THE FIXTURES CAN AND CANNOT CARRY
 * The seam was the only permitted way in, so a fixture holds exactly what the
 * seam returns and nothing else:
 *
 *   • `ad_text` is absent. `leadToChiefDto` deliberately omits it (unbounded ad
 *     creative would blow the Chief's response ceiling), so it is not
 *     recoverable and these rows carry NULL. Every field the ICP backfill reads
 *     — page_url, is_game, found_at — IS carried.
 *   • `total_ads_scraped` is absent — the DTO has no such field — so it is
 *     seeded 0 rather than invented. `total_advertisers` is set from the lead
 *     count, which the seam does report.
 *   • `source_params` is reconstructed as `{"maxLeads":<lead_count>}`, which is
 *     the only key anything reads back off it (`jobLeadCount`). The original
 *     google-ads run parameters are gone.
 *
 * These are stated in the ledger too. A rescue that quietly invented the fields
 * it could not read would be worse than one that admits the gap.
 *
 * IDEMPOTENCY
 * A job whose id is already present is skipped whole. That makes this safe on
 * every boot, which matters because it runs on every boot.
 *
 * LEAD IDS ARE PRESERVED. `job_results.id` IS `lf_lead_id` — the value the
 * Chief has already written next to its prospects — so the rows go back under
 * their original ids and the identity sequence is realigned afterwards. This is
 * why migration 1 declares those keys `GENERATED BY DEFAULT AS IDENTITY` rather
 * than `ALWAYS`.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getDb } from './db.js';
import { resolveStoredSource } from './sourceMatrix.js';
import { log } from './logger.js';

/**
 * Fixtures live beside the built code, NOT relative to the working directory.
 * `dist/rescueSeed.js` and `src/rescueSeed.ts` are both one level under the
 * package root, so this resolves to `<package>/rescue` under `node dist/…`,
 * under `tsx src/…`, and from a test booted in a throwaway cwd alike. A
 * cwd-relative path is exactly the mistake that put the database on the
 * deployment disk in the first place.
 */
const RESCUE_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'rescue');

interface RescuedLead {
  lead_id: number;
  advertiser_name: string;
  country: string;
  classification: string | null;
  store_url: string | null;
  landing_url: string | null;
  page_url: string | null;
  app_category: string | null;
  is_game: boolean | null;
  found_at: string | null;
}

interface RescuedJobDto {
  job_id: string;
  external_id: string | null;
  source: string;
  target_type: string;
  countries: string[];
  lead_count: number | null;
  state: string;
  phase: string | null;
  step: string | null;
  progress_pct: number;
  leads_found: number;
  error: string | null;
  created_at: string | null;
  started_at: string | null;
  completed_at: string | null;
  run_after: string | null;
}

interface RescueFixture {
  job_id: string;
  resolved: boolean;
  http_status?: number;
  rescued_at: string;
  external_id?: string | null;
  job?: RescuedJobDto;
  leads?: RescuedLead[];
}

export interface SeedOutcome {
  seeded: string[];
  alreadyPresent: string[];
  /** Jobs the live seam no longer resolved at rescue time — unrecoverable. */
  unrecoverable: string[];
}

const msOrNull = (iso: string | null | undefined): number | null => {
  if (!iso) return null;
  const ms = Date.parse(iso);
  return Number.isFinite(ms) ? ms : null;
};

/** The fixtures on disk, sorted so a boot's log order is stable. */
export function loadRescueFixtures(dir: string = RESCUE_DIR): RescueFixture[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => JSON.parse(readFileSync(path.join(dir, f), 'utf8')) as RescueFixture);
}

/**
 * Put the rescued jobs back. Idempotent; safe to call on every boot.
 *
 * A fixture that cannot be seeded does NOT stop the boot: the app losing one
 * historical job is bad, and the app refusing to start is worse.
 */
export async function seedRescuedChiefJobs(dir: string = RESCUE_DIR): Promise<SeedOutcome> {
  const outcome: SeedOutcome = { seeded: [], alreadyPresent: [], unrecoverable: [] };
  const fixtures = loadRescueFixtures(dir);
  if (fixtures.length === 0) return outcome;

  for (const fx of fixtures) {
    if (!fx.resolved || !fx.job) {
      outcome.unrecoverable.push(fx.job_id);
      continue;
    }
    try {
      const existing = await getDb().prepare(`SELECT id FROM jobs WHERE id = ?`).get(fx.job.job_id);
      if (existing) {
        outcome.alreadyPresent.push(fx.job_id);
        continue;
      }
      await seedOne(fx);
      outcome.seeded.push(fx.job_id);
    } catch (err) {
      log.error(`rescue-seed: could not restore ${fx.job_id} — ${(err as Error).message}`);
    }
  }

  // Realign the job_results identity AFTER any explicit-id insert, or the next
  // lead a live job writes collides with a rescued id and the insert throws.
  // Run unconditionally: it is one cheap statement and it also repairs a
  // sequence left behind by a restore from anywhere else.
  await realignJobResultsSequence();

  if (outcome.seeded.length > 0) {
    log.info(`rescue-seed: restored ${outcome.seeded.length} chief job(s) — ${outcome.seeded.join(', ')}`);
  }
  for (const id of outcome.unrecoverable) {
    log.warn(
      `rescue-seed: ${id} did not resolve on the live seam at rescue time and is NOT recoverable — ` +
        'its leads were lost with the deployment disk before this migration.',
    );
  }
  return outcome;
}

async function seedOne(fx: RescueFixture): Promise<void> {
  const job = fx.job!;
  const leads = fx.leads ?? [];

  // The wire vocabulary the Chief used ("google_ads" + "mobile") is not the
  // stored engine id ("store_first"). Resolved through the shared matrix rather
  // than hard-coded, so a seeded job reads back through uiSourceForStored as
  // exactly the source it was commanded with.
  const storedSource = resolveStoredSource(job.source as never, job.target_type as never);
  if (!storedSource) {
    throw new Error(`no engine for ${job.source} + ${job.target_type}`);
  }

  const createdAt = msOrNull(job.created_at) ?? Date.now();
  const completedAt = msOrNull(job.completed_at);

  await getDb().transaction(async (t) => {
    await t
      .prepare(
        `INSERT INTO jobs
           (id, product_type, countries, status, csv_path, error, created_at, started_at, completed_at,
            total_ads_scraped, total_advertisers, recipient_email, notification_status, created_by_user_id,
            source, source_params, phase, phase_detail, phase_updated_at, hq_zip_path, run_after,
            cancel_requested, leads_found, progress_pct)
         VALUES (?, ?, ?, ?, NULL, ?, ?, ?, ?, 0, ?, NULL, NULL, ?, ?, ?, ?, ?, ?, NULL, ?, 0, ?, ?)`,
      )
      .run(
        job.job_id,
        job.target_type,
        JSON.stringify(job.countries),
        job.state,
        job.error,
        createdAt,
        msOrNull(job.started_at),
        completedAt,
        job.leads_found,
        // Commanded jobs are owned by the machine principal, which
        // ensureChiefPrincipal() has already written by the time this runs.
        'usr_chief',
        storedSource,
        job.lead_count == null ? null : JSON.stringify({ maxLeads: job.lead_count }),
        job.phase,
        job.step,
        completedAt ?? createdAt,
        msOrNull(job.run_after),
        job.leads_found,
        job.progress_pct,
      );

    if (job.external_id != null) {
      await t
        .prepare(`INSERT INTO chief_jobs (external_id, job_id, created_at) VALUES (?, ?, ?)`)
        .run(job.external_id, job.job_id, createdAt);
    }

    for (const lead of leads) {
      await t
        .prepare(
          `INSERT INTO job_results
             (id, job_id, advertiser_name, page_url, landing_url, classification, store_url, ad_text,
              country, created_at, app_category, is_game)
           VALUES (?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, ?)`,
        )
        .run(
          lead.lead_id,
          job.job_id,
          lead.advertiser_name,
          lead.page_url,
          lead.landing_url,
          lead.classification,
          lead.store_url,
          lead.country,
          msOrNull(lead.found_at) ?? createdAt,
          lead.app_category,
          lead.is_game == null ? null : lead.is_game ? 1 : 0,
        );
    }
  });
}

/**
 * Push the `job_results` identity past every id currently in the table.
 *
 * `setval(..., n, true)` means "n is used, hand out n+1 next". The COALESCE
 * covers an empty table, where the sequence must be left reporting that 1 has
 * NOT been used yet — hence the `false` third argument in that branch.
 */
async function realignJobResultsSequence(): Promise<void> {
  await getDb().exec(`
    SELECT CASE
      WHEN (SELECT MAX(id) FROM job_results) IS NULL
        THEN setval(pg_get_serial_sequence('job_results', 'id'), 1, false)
      ELSE setval(pg_get_serial_sequence('job_results', 'id'), (SELECT MAX(id) FROM job_results), true)
    END;
  `);
}
